### ISSUE TITLE
Travel/Leave

### ISSUE THREAD

**Issue by escowles** [pulibrary/drds_sprints#3]
Create a new Rails app to replace the Travel request app, and also allow requesting vacation time.

**Comment by escowles** [comment]
Tentatively scheduled for 4/22, including Carolyn, Shaun, Axa, and one more from DRDS.

**Comment by jpstroop** [comment]
I scratched this together a while ago, in case it's helpful: https://docs.google.com/document/d/1Cs6N6fJ5k3LBvkCCs2Kc3ma8EtnWxrgXWXGxjR-ZdoU/edit#
